name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub 소스 가져오기
        uses: actions/checkout@v4

      - name: Node 설치
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 의존성 설치
        run: npm ci

      - name: 빌드
        run: npm run build

      - name: EC2에 빌드 결과 전송
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST_FRONT }}
          username: ${{ secrets.EC2_USER_FRONT }}
          key: ${{ secrets.EC2_KEY_FRONT }}
          source: "dist/*"
          target: "/home/ubuntu/frontend-dist"

      - name: Nginx에 배포
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST_FRONT }}
          username: ${{ secrets.EC2_USER_FRONT }}
          key: ${{ secrets.EC2_KEY_FRONT }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/frontend-dist/* /var/www/html/
            sudo systemctl restart nginx
